--- 
- name: Configure Web Servers 
  hosts: web 
  become: true
  vars_files:
    - group_vars/vars.yaml
  tasks: 
    - name: Display OS info 
      ansible.builtin.debug:
        msg: "{{ ansible_facts ['distribution'] }}"
      when: 
        - ansible_facts['distribution'] != "Ubuntu"  
        - ansible_facts['distribution'] != "Amazon" 
    - name: Install {{ nginx_package }} and {{ unzip_package }} for Ubuntu 
      ansible.builtin.apt: 
        name: 
          - "{{ nginx_package }}"
          - "{{ unzip_package }}"  
        state: present 
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"
    - name: Install {{ nginx_package }} and {{ unzip_package }} for "Amazon"
      ansible.builtin.dnf:
        name: 
          - "{{ nginx_package }}"
          - "{{ unzip_package }}" 
        update_cache: true
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure Nginx is running 
      ansible.builtin.systemd_service: 
        name: nginx 
        state: started 
        enabled: true
    
    - name: Download the URL 
      ansible.builtin.get_url:
        url: "{{ template_url }}"
        dest: /tmp/artcore.zip
        mode: '0644'

    - name: Extract all files 
      ansible.builtin.unarchive:
        src: "{{ zip_path }}" 
        dest: "{{ extract_path }}"
        remote_src: yes 

    - name: Copy template files to Ubuntu
      ansible.builtin.copy:
        src: "{{ template_folder }}"
        dest: "{{ ubuntu_web_root }}"
        remote_src: true
      when: ansible_facts['os_family'] == "Debian"
      notify: Restart nginx

    - name: Copy template files to Amazon Linux
      ansible.builtin.copy:
        src: "{{ template_folder }}"
        dest: "{{ amazon_web_root }}"
        remote_src: true
      when: ansible_facts['os_family'] == "RedHat"
      notify: Restart nginx

    - name: Remove Zip files 
      ansible.builtin.file:
        path: "{{ zip_path }}"
        state: absent 

    - name: Remove copy files 
      ansible.builtin.file:
        path: "{{ template_folder }}"
        state: absent 
  handlers:
    - name: Restart nginx 
      ansible.builtin.systemd_service:
        name: nginx 
        state: restarted 

        